Remove Deno shims
KnorpelSenf/oson pull request #8
Opened 2023-07-18 20:16 UTC by PonomareVlad

Proposed to remove Deno shims — https://github.com/grammyjs/conversations/pull/82#issuecomment-1639540965

[Test source](https://github.com/PonomareVlad/grammY-Test/tree/vercel-edge-oson)

2023-07-19 11:19 UTC, wojpawlik approved these changes
Closes #7.

@KnorpelSenf what's the lightweight tag for?
https://github.com/KnorpelSenf/oson/blob/0fe5862fbb67181b902c5f2b1d50979079f0a369/build.ts#L47-L50

2023-08-07 08:09 UTC, KnorpelSenf approved these changes

2023-08-07 08:10 UTC, KnorpelSenf commented
I don't see why we should take web-compatible code, inject a bunch of weird things so it can run on Node, and then use the Node-compat mode of web runtimes?

2023-08-07 08:11 UTC, KnorpelSenf commented
But then again, I care so little about what happens to the Node package, that I might as well merge. As long as the web-compatible Deno build is clean, I'm happy. Sorry, future self :)

2023-08-07 08:17 UTC, KnorpelSenf commented
> Closes #7.
> 
> @KnorpelSenf what's the lightweight tag for?
> 
> https://github.com/KnorpelSenf/oson/blob/0fe5862fbb67181b902c5f2b1d50979079f0a369/build.ts#L47-L50

It tags a new release

2023-08-07 08:17 UTC, PonomareVlad commented
@KnorpelSenf [This](https://www.npmjs.com/package/@ponomarevlad/o-son/v/1.0.1-web.1?activeTab=code) will happen

2023-08-07 08:21 UTC, KnorpelSenf commented
> @KnorpelSenf [This](https://www.npmjs.com/package/@ponomarevlad/o-son/v/1.0.1-web.1?activeTab=code) will happen

What do you mean?

2023-08-07 08:26 UTC, PonomareVlad commented
> > @KnorpelSenf [This](https://www.npmjs.com/package/@ponomarevlad/o-son/v/1.0.1-web.1?activeTab=code) will happen
> 
> 
> 
> What do you mean?

Just exclude test sources (and polyfills for them) from npm package and it will be look cleaner 🙂

2023-08-07 08:41 UTC, KnorpelSenf commented
In package.json?

Do you mean I should do it? Do you mean this PQ already does it? Do you mean that this would be something to solve in the future? Are you responding to anything I said? I can't quite follow tbh

2023-08-07 08:52 UTC, PonomareVlad commented
@KnorpelSenf I just woke up, I'm sorry, caffeine will work now and I'll add it to PQ 🙃

2023-08-07 09:42 UTC, PonomareVlad commented
@KnorpelSenf If we disable test then got [this result](https://www.npmjs.com/package/@ponomarevlad/o-son/v/1.0.1-web.2?activeTab=code)

This seems like simplest way to eliminate test sources (and shims with them), but if test step is important, then we need something else

Maybe we can run build in two iterations — first with test and second without it for minimize ?

2023-08-07 09:47 UTC, wojpawlik commented
https://github.com/denoland/dnt#denotest-only-shim

@KnorpelSenf annotated tags are supposed to be used fot releases

2023-08-07 12:24 UTC, KnightNiwrem requested changes
Ref: https://t.me/grammyjs/155170

We cannot release a change that would break conversations for all non-VercelEdge Node users.

2023-08-07 12:43 UTC, KnightNiwrem approved these changes

2023-08-07 12:44 UTC, PonomareVlad commented
Maybe we need to pin minimal `node` version for reliability ?

2023-08-18 22:45 UTC, KnorpelSenf commented
I had to do some adjustments which were partially included here. Could you resolve the conflicts? I'll get back to this after that.

2025-06-15 08:55 UTC, KnorpelSenf commented
After migrating to JSR, this became obsolete. Closing.

2025-06-15 08:55 UTC, closed without merging